/*
 * API TroubleTicket
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RelatedObject
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-29T18:35:10.093-02:00")
public class RelatedObject {
  @JsonProperty("involvement")
  private String involvement = null;

  @JsonProperty("reference")
  private String reference = null;

  public RelatedObject involvement(String involvement) {
    this.involvement = involvement;
    return this;
  }

   /**
   * Get involvement
   * @return involvement
  **/
  @ApiModelProperty(value = "")
  public String getInvolvement() {
    return involvement;
  }

  public void setInvolvement(String involvement) {
    this.involvement = involvement;
  }

  public RelatedObject reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(value = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RelatedObject relatedObject = (RelatedObject) o;
    return Objects.equals(this.involvement, relatedObject.involvement) &&
        Objects.equals(this.reference, relatedObject.reference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(involvement, reference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RelatedObject {\n");
    
    sb.append("    involvement: ").append(toIndentedString(involvement)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

