/*
 * API TroubleTicket
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.Hub;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HubApi
 */
@Ignore
public class HubApiTest {

    private final HubApi api = new HubApi();

    
    /**
     * hubCreate
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hubCreateTest() {
        Hub hub = null;
        Hub response = api.hubCreate(hub);

        // TODO: test validations
    }
    
    /**
     * hubDelete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hubDeleteTest() {
        String hubId = null;
        api.hubDelete(hubId);

        // TODO: test validations
    }
    
    /**
     * hubFind
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hubFindTest() {
        List<Hub> response = api.hubFind();

        // TODO: test validations
    }
    
    /**
     * hubGet
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void hubGetTest() {
        String hubId = null;
        Hub response = api.hubGet(hubId);

        // TODO: test validations
    }
    
}
