/*
 * API TroubleTicket
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.TroubleTicket;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TroubleTicketApi
 */
@Ignore
public class TroubleTicketApiTest {

    private final TroubleTicketApi api = new TroubleTicketApi();

    
    /**
     * troubleTicketCreate
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void troubleTicketCreateTest() {
        TroubleTicket troubleTicket = null;
        TroubleTicket response = api.troubleTicketCreate(troubleTicket);

        // TODO: test validations
    }
    
    /**
     * troubleTicketFind
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void troubleTicketFindTest() {
        String fields = null;
        List<TroubleTicket> response = api.troubleTicketFind(fields);

        // TODO: test validations
    }
    
    /**
     * troubleTicketGet
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void troubleTicketGetTest() {
        String troubleTicketId = null;
        String fields = null;
        TroubleTicket response = api.troubleTicketGet(troubleTicketId, fields);

        // TODO: test validations
    }
    
    /**
     * troubleTicketPatch
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void troubleTicketPatchTest() {
        String troubleTicketId = null;
        TroubleTicket troubleTicket = null;
        TroubleTicket response = api.troubleTicketPatch(troubleTicketId, troubleTicket);

        // TODO: test validations
    }
    
    /**
     * troubleTicketUpdate
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void troubleTicketUpdateTest() {
        String troubleTicketId = null;
        TroubleTicket troubleTicket = null;
        TroubleTicket response = api.troubleTicketUpdate(troubleTicketId, troubleTicket);

        // TODO: test validations
    }
    
}
